{
  "_id": {
    "$oid": "605a01016cf0a13ef548150d"
  },
  "author_association": "MEMBER",
  "issue_url": "https://api.github.com/repos/hexojs/hexo/issues/3370",
  "updated_at": "2018-12-17T15:05:10Z",
  "performed_via_github_app": null,
  "html_url": "https://github.com/hexojs/hexo/issues/3370#issuecomment-447876687",
  "created_at": "2018-12-17T15:05:10Z",
  "id": 447876687,
  "body": "@tomap @tcrowe \r\nThe CI failed reason may not caused by lock file. I open #3392  about that.",
  "user": {
    "gists_url": "https://api.github.com/users/yoshinorin/gists{/gist_id}",
    "repos_url": "https://api.github.com/users/yoshinorin/repos",
    "following_url": "https://api.github.com/users/yoshinorin/following{/other_user}",
    "starred_url": "https://api.github.com/users/yoshinorin/starred{/owner}{/repo}",
    "login": "yoshinorin",
    "followers_url": "https://api.github.com/users/yoshinorin/followers",
    "type": "User",
    "url": "https://api.github.com/users/yoshinorin",
    "subscriptions_url": "https://api.github.com/users/yoshinorin/subscriptions",
    "received_events_url": "https://api.github.com/users/yoshinorin/received_events",
    "avatar_url": "https://avatars.githubusercontent.com/u/11273093?v=4",
    "events_url": "https://api.github.com/users/yoshinorin/events{/privacy}",
    "html_url": "https://github.com/yoshinorin",
    "site_admin": false,
    "id": 11273093,
    "gravatar_id": "",
    "node_id": "MDQ6VXNlcjExMjczMDkz",
    "organizations_url": "https://api.github.com/users/yoshinorin/orgs"
  },
  "url": "https://api.github.com/repos/hexojs/hexo/issues/comments/447876687",
  "node_id": "MDEyOklzc3VlQ29tbWVudDQ0Nzg3NjY4Nw=="
}