{
  "_id": {
    "$oid": "60720d1343dd71267de27f31"
  },
  "author_association": "MEMBER",
  "issue_url": "https://api.github.com/repos/python-trio/trio/issues/654",
  "updated_at": "2018-09-12T06:12:10Z",
  "performed_via_github_app": null,
  "html_url": "https://github.com/python-trio/trio/pull/654#issuecomment-420524418",
  "created_at": "2018-09-12T06:12:10Z",
  "id": 420524418,
  "body": "@Zac-HD okay, at least we tried. ðŸ˜› \r\n\r\n@njsmith Yeah, this is noted in the pip-tools 2.0.0 release notes:\r\n\r\n> The pip environment markers on top-level requirements in the source file (requirements.in) are now properly handled and will only be processed in the right environment (#647). Thanks @JoergRittinger\r\n\r\nSo, yeah, thanks @JoergRittinger. :)\r\n\r\nI added typed_ast with its environment markers in the .in file. This has fixed the PyPy builds. Please take a look.",
  "user": {
    "gists_url": "https://api.github.com/users/pquentin/gists{/gist_id}",
    "repos_url": "https://api.github.com/users/pquentin/repos",
    "following_url": "https://api.github.com/users/pquentin/following{/other_user}",
    "starred_url": "https://api.github.com/users/pquentin/starred{/owner}{/repo}",
    "login": "pquentin",
    "followers_url": "https://api.github.com/users/pquentin/followers",
    "type": "User",
    "url": "https://api.github.com/users/pquentin",
    "subscriptions_url": "https://api.github.com/users/pquentin/subscriptions",
    "received_events_url": "https://api.github.com/users/pquentin/received_events",
    "avatar_url": "https://avatars.githubusercontent.com/u/42327?v=4",
    "events_url": "https://api.github.com/users/pquentin/events{/privacy}",
    "html_url": "https://github.com/pquentin",
    "site_admin": false,
    "id": 42327,
    "gravatar_id": "",
    "node_id": "MDQ6VXNlcjQyMzI3",
    "organizations_url": "https://api.github.com/users/pquentin/orgs"
  },
  "url": "https://api.github.com/repos/python-trio/trio/issues/comments/420524418",
  "node_id": "MDEyOklzc3VlQ29tbWVudDQyMDUyNDQxOA=="
}