{
  "_id": {
    "$oid": "6071e39d43dd71267de1c3f5"
  },
  "author_association": "NONE",
  "issue_url": "https://api.github.com/repos/pydanny/cookiecutter-django/issues/1118",
  "updated_at": "2017-04-12T17:32:03Z",
  "performed_via_github_app": null,
  "html_url": "https://github.com/pydanny/cookiecutter-django/issues/1118#issuecomment-293651573",
  "created_at": "2017-04-12T17:32:03Z",
  "id": 293651573,
  "body": "@pydanny Can you help me get caught up on this? I think you generate a .idea directory when used for real-sies but not under CI? Not sure I quite know yet the question.",
  "user": {
    "gists_url": "https://api.github.com/users/pauleveritt/gists{/gist_id}",
    "repos_url": "https://api.github.com/users/pauleveritt/repos",
    "following_url": "https://api.github.com/users/pauleveritt/following{/other_user}",
    "starred_url": "https://api.github.com/users/pauleveritt/starred{/owner}{/repo}",
    "login": "pauleveritt",
    "followers_url": "https://api.github.com/users/pauleveritt/followers",
    "type": "User",
    "url": "https://api.github.com/users/pauleveritt",
    "subscriptions_url": "https://api.github.com/users/pauleveritt/subscriptions",
    "received_events_url": "https://api.github.com/users/pauleveritt/received_events",
    "avatar_url": "https://avatars.githubusercontent.com/u/455142?v=4",
    "events_url": "https://api.github.com/users/pauleveritt/events{/privacy}",
    "html_url": "https://github.com/pauleveritt",
    "site_admin": false,
    "id": 455142,
    "gravatar_id": "",
    "node_id": "MDQ6VXNlcjQ1NTE0Mg==",
    "organizations_url": "https://api.github.com/users/pauleveritt/orgs"
  },
  "url": "https://api.github.com/repos/pydanny/cookiecutter-django/issues/comments/293651573",
  "node_id": "MDEyOklzc3VlQ29tbWVudDI5MzY1MTU3Mw=="
}